### ISSUE TITLE
Update Favicon + Title

### ISSUE THREAD

**Issue by jeanpaulsio** [hoist-labs/url-shortener#6]
# Summary

We currently have no favicon and the application's shows the default "UrlShortener"

![image](https://user-images.githubusercontent.com/8096483/124021993-14fcb580-d9a1-11eb-8a6e-ef765bb91bbf.png)

## Acceptance Criteria

- [ ] Add a favicon. It can just be a png of 🔗
- [ ] Update the page title to something like "Hoist URL Shortener"

**Comment by danger-ahead** [comment]
Hi, I can help. Please consider assigning me!
